### ISSUE TITLE
Rename 'lego' repo to 'oui'

### ISSUE THREAD

**Issue by tomgenoni** [optimizely/oui#130]
Can we dupe the repo so `lego` and `oui` and briefly live simultaneously? Not sure the best way to handle the switch.

**Comment by danoc** [comment]
I think there's a way we can do it without needing to clone the repository. GitHub is pretty good about doing redirects and the fact that we're using NPM might help as well. I don't think NPM cares about the repository URL.

I'll assign this one to myself.

**Comment by danoc** [comment]
It's likely a breaking change once we rename the NPM module to be `optimizely-oui`, not `optimizely-lego`. I think we can do this in two steps.

**Comment by tscanlin** [comment]
can this be closed now?
