### ISSUE TITLE
Add `.lego--date` class to complement `.oui--search` for date inputs.

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#152]
Marco wanted to add this to the Optimizely app and I think it should be part of Core. UXD-186 is tracking the tech debt we added by temporarily adding it to the p13n SCSS.

<img width="609" alt="screenshot 2015-11-17 17 11 10" src="https://cloud.githubusercontent.com/assets/916038/11229872/bffab022-8d4e-11e5-9b28-b6bccb2fa262.png">

cc: @tscanlin, @tomgenoni, @kwalker3690

**Comment by ghigo** [comment]
You might also want to update the scheduler style once it's done.
![screen shot 2015-11-17 at 5 20 28 pm](https://cloud.githubusercontent.com/assets/185571/11229989/b3c60508-8d4f-11e5-856e-084fae1962f8.png)

**Comment by danoc** [comment]
Good thought. Thanks!

**Comment by danoc** [comment]
@tomgenoni – Do you think we should add this? What would you call it?

I feel like it would complement this well:

<img width="889" alt="screenshot 2016-02-19 09 54 04" src="https://cloud.githubusercontent.com/assets/916038/13184089/c21a76a0-d6ee-11e5-9ede-f1ca9dddb99b.png">

**Comment by daverau-optimizely** [comment]
Will revisit next time we have a need for date inputs as a React component.
