### ISSUE TITLE
Create a `devel` branch to merge PRs into

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#153]
Random thought: We often run into problems where we want to change Core and ship code quickly but we can't because there are many unreleased breaking changes. We should consider creating a `devel` branch to merge code into and only merge into `master` when ready to release a new version.

This would free up `master` so we can quickly ship non-breaking changes while breaking changes can remain in the queue to be released (on `devel`, but not in `master`).

Thoughts? @tomgenoni @tscanlin @kwalker3690

**Comment by tscanlin** [comment]
+1 awesome idea @danoc :)

**Comment by danoc** [comment]
Done! See `CONTRIBUTING.md` for info.
