### ISSUE TITLE
Flexbox container not inheriting height of children in IE 10 + 11 under certain circumstances

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#155]
There is a flexbox bug in IE10 and IE11 that prevents the parent from inheriting the height of the child. It behaves almost as if the parent only had elements that were floated and never cleared.

AFAIK, it happens when:

1. Parent has `display: flex` and `flex-direction: column`.
2. All of the direct children have `display: flex` and `flex: 1`.
3. The parent does not have a fixed height.

https://roland.codes/blog/ie-flex-collapse-bug/

Currently I think the fix is to add `flex-basis: auto` to the end of `.flex--1`, not the `flex($num)` mixin, but I'm still investigating. This caused problems on our signin page and is tracked in AB-1013.

**Comment by danoc** [comment]
The proposed change breaks the dashboard in IE11, so no good. :cry:

**Comment by tomgenoni** [comment]
Is this an active issue?

**Comment by danoc** [comment]
Going to close this. Waaay too much of a rabbit-hole that I'm not trying to get into.
