### ISSUE TITLE
Rename `src/core` to `src/scss`

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#183]
Makes more sense IMO. The folder currently looks like this:

* `src/`
  * `core/`
  * `js/`

**Comment by tomgenoni** [comment]
Yeah, have no disagreement with that. I'd suggest we further change `core.scss` and other `core-` files to `oui`. I can create a separate issue for that.

**Comment by tomgenoni** [comment]
I changed `scr/core` to `scr/oui` as that will make reference to it in products that use it clean/clear. E.g,

```
@import 'oui/oui-variables';
@import 'design-dot/design-dot-variables';
```
