### ISSUE TITLE
Remove outline from inputs of type number

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#217]
![screenshot 2016-01-25 13 34 15](https://cloud.githubusercontent.com/assets/916038/12565218/5dc5551a-c368-11e5-9573-817446d7a554.png)

It would be great if `input`'s with `type="number"` were right-aligned automatically and the default padding was changed to better suit the input.

**Comment by tomgenoni** [comment]
agreed. didn't account for that form type.

**Comment by tomgenoni** [comment]
@danoc Wouldn't `<input type="number" class="text-input text--right" />` accomplish the same thing? Seems like you might not always want right-aligned numbers.

**Comment by danoc** [comment]
Yeah, I agree. Can't reproduce my original issue but found a new one and renamed the issue.
