### ISSUE TITLE
Select left-padding is inconsistent with inputs

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#220]
See screenshot:
<img width="711" alt="screenshot 2016-01-26 16 36 30" src="https://cloud.githubusercontent.com/assets/916038/12600087/b9396a88-c44b-11e5-82b7-51c35fed40bc.png">

**Comment by tomgenoni** [comment]
![screen shot 2016-01-26 at 4 54 16 pm](https://cloud.githubusercontent.com/assets/1171072/12600403/5acb080a-c44e-11e5-94e1-47362f4b9b0f.png)

**Comment by tomgenoni** [comment]
In PR #221
