### ISSUE TITLE
Clean up _reset.scss

### ISSUE THREAD

**Issue by tomgenoni** [optimizely/oui#226]
There's code in there that applies to older browsers we don't support.

**Comment by danoc** [comment]
I wonder if normalize makes more sense? http://stackoverflow.com/a/8357635/316602

I've always been a big fan of it but it might be too late/hard to integrate at this point.

**Comment by tomgenoni** [comment]
Our reset does some of this so it's not far off. I wouldn't object to converting it to normalize if you want to. Would probably just mean moving some code around so maybe not so bad?

**Comment by danoc** [comment]
It might mess with the margins on elements? Not so sure.
