### ISSUE TITLE
Move `no-border` classes to `_borders.scss`?

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#228]
Small change but makes a bit more sense IMO.

**Comment by tomgenoni** [comment]
One thing we want to be careful about is location of trumps, or if they are supposed to be trumps in the first place.

**Comment by daverau-optimizely** [comment]
I dig this, was just looking for a no-border helper yesterday.

**Comment by danoc** [comment]
@tomgenoni Fair point but FWIW they are already trumps in: https://github.com/optimizely/oui/blob/fe832e3daad0f30f9f1ecd71ab401a731fd553b0/src/oui/partials/trumps/_layout.scss#L131-L149

**Comment by tomgenoni** [comment]
Sounds good. Go for it.
