### ISSUE TITLE
Add the primary and secondary colors to OUI

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#230]
Spoke with @tomgenoni and @kwalker3690 about this in person.

http://design.optimizely.com/brand/colors.html

**Comment by danoc** [comment]
Here is a map of the colors.

```
// Brand colors
// http://design.optimizely.com/brand/colors.html

$brand-colors: (
  primary: (
    brand-blue: #0081BA,
    charcoal: #4C4C4C,
    karl: #F7F7F7
  ),
  secondary: (
    deboce: #FD6B58,
    marina: #84CFCA,
    oakland: #F4B852,
    haight: #54BC4B,
    mission: #A3356E,
    richmond: #869FAB,
    seacliff: #EFE9DC
  )
);
```

**Comment by tomgenoni** [comment]
How would this integrate with the existing $color object (mainly the blue)?

**Comment by danoc** [comment]
@tomgenoni – I think the existing brand blue would should from this map instead of repeating it twice.

**Comment by danoc** [comment]
@tomgenoni, @kwalker3690 – Do you think we should close this or discuss at OBA (and invite product designers)? Seems like we are using more and more colors from design-dot and it'd be nice to have a discussion about how many colors we need and want to support in our projects.
