### ISSUE TITLE
Make it more obvious that the documentation is linked to in the README

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#231]
Based on feedback from Becca in #oui on Slack.

**Comment by nathanjessen** [comment]
I don't see a link to documentation. Is there a styleguide or something with a visual respresentation of the components? I see commenting at the top of each sass file and I'm wondering if that is just for the developer or if that is being used by a living styleguide.

**Comment by danoc** [comment]
@nathanjessen – There's a link as a badge in the top of the README, but #250 will make it more obvious.
