### ISSUE TITLE
Attention bar close button class doesn't make it vertically align with text

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#233]
This is super nit-picky, but here's a screenshot from the docs.

![screenshot 2016-02-04 10 42 20](https://cloud.githubusercontent.com/assets/916038/12825613/12287b48-cb2c-11e5-9f97-5139e2e599c7.png)

**Comment by tomgenoni** [comment]
It was because of multiline.

![screen shot 2016-02-04 at 10 48 43 am](https://cloud.githubusercontent.com/assets/1171072/12825814/e55da362-cb2c-11e5-88d9-8088c017145c.png)
