### ISSUE TITLE
Get rid of vendor prefixes

### ISSUE THREAD

**Issue by HugoGiraudel** [optimizely/oui#240]
I would argue it is not OUI’s role to output vendor prefixes, or at least not like this. As far as I can tell, you just re-implemented the prefixing system from Bourbon (or was it Compass? can’t recall) but that seems like a bad idea to me (also because any prefixing system that takes 300 lines is a bad system in the first place anyway).

There are good reasons why Autoprefixer is so popular, and that’s not only because it makes dealing with vendor prefixes a breeze. It is because it is always up-to-date, and it offers a grained control over what to output and what not. Vendor prefixing makes complete sense as a postprocessing step, not a preprocessing one.

I would recommend you do not include vendor prefixes at all in OUI, and let people plug in Autoprefixer. Best case scenario, you’ll push more people to use Autoprefixer and that is good for the web. It would also allow you to remove tons of code from your lib, which means easier maintenance.

I am willing to submit a PR to remove all the prefixes if you’d like to.

**Comment by tomgenoni** [comment]
Thanks for the offer. I set this up on a branch yesterday using `gulp-autoprefixer` and it appeared to work as expected. We had a few minor hacks that I'll have to test out but this would remove some of the complexity of our code.

**Comment by HugoGiraudel** [comment]
If you are setting Gulp just for autoprefixing, I’d suggest you don’t and simply use autoprefixer through CLI via a npm script. Happy to do that for you if you need it.

**Comment by tomgenoni** [comment]
We have a whole set of gulp tasks https://github.com/optimizely/oui/tree/devel/gulp

The prefixer is easily added on.

**Comment by HugoGiraudel** [comment]
Alright then.
