### ISSUE TITLE
Consider accessibility in your examples

### ISSUE THREAD

**Issue by HugoGiraudel** [optimizely/oui#243]
There is no consideration for accessibility in your markup snippets (top comment of each component). I know OUI is a Sass framework and not a front-end one, but developers are likely to copy-paste these snippets into their code. By adding all the missing attributes and aria considerations, you would help people building accessible and friendly component.

And this is precisely why you built OUI in the first place I’d say. :)

**Comment by danoc** [comment]
Hi @HugoGiraudel,

Thanks for submitting this issue and sorry for the delayed response. We're finally moving towards building OUI React components and I'll be working to bake accessibility into those (and update the markup snippets in the SCSS files).

I've created a more detailed issue (#382) to track this effort, so I'll close this one.

Thanks again for the feedback! 😄
