### ISSUE TITLE
Add namespace option for classes in javascript

### ISSUE THREAD

**Issue by tomgenoni** [optimizely/oui#255]
Currently the javascript injects popovers and poptips with no namespace. They will fail if the Sass has been namespaced, e.g., `.lego-pop`.

**Comment by daverau-optimizely** [comment]
I ran into this for Preview and wanted to chat with you about a good solution @tomgenoni

**Comment by tomgenoni** [comment]
My current plan was to add a flag when compiling the JS in the OUI repo. So if you wanted `lego-` prefix on the classes in the JS you would run:

`gulp js --namespace=lego-` 

This would output `lego-oui.min.js` in which all classes for poptips/popovers contain the `lego-` prefix.

Happy to do it a different way though if we think of something better.
