### ISSUE TITLE
Move layout files into a new layout directory

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#258]
These files relate to layout:

* partials/objects/_array.scss
* partials/objects/_button-group.scss
* partials/objects/_button-row.scss
* partials/elements/_clearfix.scss
* partials/elements/_flexbox.scss
* partials/components/_grid.scss
* partials/components/_island.scss
* partials/components/_matrix.scss

@daverau-optimizely, @tomgenoni – Should we move them all into a new `layout/` directory?

**Comment by tomgenoni** [comment]
I like this. They aren't all equally abstract which I think was my initial hesitation — `button-group` is specific to buttons — but they are all alike in the sense that they are containers that establish layout containers that you fill with stuff. To me that's enough of a justification/explanation.

**Comment by danoc** [comment]
@tomgenoni – Yeah, I agree. Do you think the solution is to abstract the button layout files?

**Comment by tomgenoni** [comment]
I'm inclined to say no. Seems like no matter what we do there will be a little mental friction: either we have an abstract wrapper that isn't semantically tied to buttons or we have specific one (like we have now) that seems too specific given the other files in the `layout` dir. Plus, I don't see how `button-row` could abstracted as it expects buttons, removes border-radiuses, moves margins by -1px, etc.

**Comment by danoc** [comment]
Yeah, good point. I agree.

**Comment by danoc** [comment]
This is a "Patch" change because the files are only listed within `_oui-partials.scss`.
