### ISSUE TITLE
Rename files to either be plural or singular

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#270]
@tscanlin pointed out that we're a bit inconsistent in our file naming conventions.

**Comment by tomgenoni** [comment]
I prefer singular.

**Comment by danoc** [comment]
Cool. I don't have much of a preference. I'll do this after reshuffling the files in the other issues.

**Comment by tomgenoni** [comment]
Most names work either way, like `_tables.scss` but, e.g., `_codes.scss` sounds odd.

**Comment by tomgenoni** [comment]
When https://github.com/optimizely/oui/pull/337 is complete I can work on this one.
