### ISSUE TITLE
Add support for sublists within block list

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#283]
@furiousat7 and I are building a block list that has a concept of sections. The existing block list works well if the section name ("Custom Events", in this case) is hardcoded as another `<li>`.

```html
<ul>
  <li class="section-name">Section title</li>
  <li>Child 1</li>
  <li>Child 2</li>
</ul>
```

<img width="719" alt="screenshot 2016-02-25 11 06 59" src="https://cloud.githubusercontent.com/assets/916038/13330909/ebe83f92-dbaf-11e5-82ce-57783c854ce7.png">

The existing component breaks when the section name is part of an object that is added to the codebase in a loop since that would require nesting.

```js
var obj = {
  'Section 1 Title': ['Child 1', 'Child 2'],
  'Section 2 Title': ['Child 3', 'Child 4'],
};
```

```html
<ul>
  <li>
    <div class="section-name">Section 1 Title</div>
    <ul>
      <li>Child 1</li>
      <li>Child 2</li>
    </ul>
  </li>
  <li>
    <div class="section-name">Section 2 Title</div>
    <ul>
      <li>Child 3</li>
      <li>Child 4</li>
    </ul>
  </li>
</ul>
```
That outputs something like this:

<img width="687" alt="screenshot 2016-02-25 11 16 25" src="https://cloud.githubusercontent.com/assets/916038/13331197/4417454a-dbb1-11e5-9020-e31e1240de8a.png">

Here's an approach we can take to support these nested lists:
http://codepen.io/danoc/pen/grYexM

cc: @tomgenoni

**Comment by tomgenoni** [comment]
Why not keep the lists separate? Only new CSS is for the title.
http://codepen.io/anon/pen/zqOJar

```
<div class="block-list-group">
  <div class="title">title</div>
  <ul class="block-list">
  <li>
    <a href="#" class="block-list__link">Foo</a>
  </li>
  <li>
    <a href="#" class="block-list__link">Bar</a>
    </li>
  </ul>
  <div class="title">title</div>
  <ul class="block-list">
  <li>
    <a href="#" class="block-list__link">Foo</a>
  </li>
  <li>
    <a href="#" class="block-list__link">Bar</a>
    </li>
  </ul>
</div>
```

**Comment by danoc** [comment]
Yeah, that worked perfectly!
