### ISSUE TITLE
Link to compiled css in README doesn't work

### ISSUE THREAD

**Issue by kwalker3690** [optimizely/oui#293]
<link rel="stylesheet" href="//d2uaiq63sgqwfs.cloudfront.net/8.0.0/oui.css">

Needs `https:` in front of it

**Comment by tomgenoni** [comment]
It works for me as is. 

```
<link rel="stylesheet" href="//d2uaiq63sgqwfs.cloudfront.net/8.0.0/oui.css">
```

Can you show me how yours failed?

**Comment by tomgenoni** [comment]
So you were probably using this locally and not through a server. But there's no reason NOT to add `https:` so we'll add it as requested.
