### ISSUE TITLE
Need a white-space:normal option for lego-dropdown

### ISSUE THREAD

**Issue by kwalker3690** [optimizely/oui#301]
<img width="277" alt="screen shot 2016-03-09 at 9 06 00 am" src="https://cloud.githubusercontent.com/assets/2287470/13643534/3d4a7898-e5d6-11e5-8588-b467d8d39b02.png">
White space is set to "no-wrap" on all dropdowns, however I have a dropdown with descriptions in it that I'd like to make wrap. Idea is to add a helper class like `white-space--normal` to add to `dropdown`. Thoughts @danoc @tomgenoni ?

**Comment by tomgenoni** [comment]
We have a `.nowrap` class in https://github.com/optimizely/oui/blob/devel/src/oui/partials/trumps/_type.scss That work?

**Comment by kwalker3690** [comment]
Yep that's exactly what I needed, missed that in my search

**Comment by tomgenoni** [comment]
There is already a `.wrap` class in p13n. That should probably be fixed but for the short term I'll add a `.wrap-text` class to address this.
