### ISSUE TITLE
Add progress dots for loading

### ISSUE THREAD

**Issue by kwalker3690** [optimizely/oui#347]
Request from designers to have a second type of loading signifier other than `.spinner`. Accepted idea is to implement three animated progress dots.

**Comment by daverau-optimizely** [comment]
Good idea @kwalker3690 — when should we use the three dots vs the spinner?

**Comment by kwalker3690** [comment]
I think it's kind of up to our discretion at this point, or we can urge the designers to make harder rules around it. I was trying to use the spinner on a gray background, and it was not visible, so I needed another option. Another good use case for the three dots is for smaller fields, like a table row, where a spinner doesn't fit as well

**Comment by kwalker3690** [comment]
@daverau-optimizely A standard me and a few designers think makes sense is to use the spinner for full page reloads only and the dots for loading segments of a page
