### ISSUE TITLE
Styling for :focus

### ISSUE THREAD

**Issue by kwalker3690** [optimizely/oui#355]
@zleach you mentioned wanting to get rid of the default styling that is shown on `:focus` for things like buttons. We should not get rid of it because it is essential to accessibility, but instead design a style for it that is better than the standard.

**Comment by danoc** [comment]
@kwalker3690 – Here is a look into the various approaches: http://codepen.io/danoc/full/yOvKav/

(The bottom one is the ideal solution.)

**Comment by kwalker3690** [comment]
Oh the bottom one feels PERRRRFECT
