### ISSUE TITLE
Select elements have default appearance on them in Chrome

### ISSUE THREAD

**Issue by kwalker3690** [optimizely/oui#358]
![image](https://cloud.githubusercontent.com/assets/2287470/14327916/5680d694-fbe9-11e5-92df-a7cfcf1b7aba.png)

Looks like `appearance: none` is not getting vendor prefixes on it

**Comment by tomgenoni** [comment]
Is this in the app?

**Comment by kwalker3690** [comment]
No its in the documentation for 10.0.0, @danoc thinks the docs may be missing autoprefixer

**Comment by danoc** [comment]
@tomgenoni – Yeah, I realized I forgot to run autoprefixer for the 10.0.0 docs so it's probably all borked in non-Chrome. 😢 

Will fix that soon!

**Comment by danoc** [comment]
This was a documentation only issue and has been fixed.
http://design.optimizely.com/docs/oui/10.0.0/#elements-forms
