### ISSUE TITLE
Implement a better release process to make upgrades less painful

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#360]
OUI has been releasing often and, due to the "everything is global" nature of CSS, many changes are not backwards compatible. This leads to _huge_ releases full of breaking changes. 

**Problems with the current system:**

1. Upgrading the Optimizely app to support a large release is painful and error-prone.
2. "Unreleased" breaking changes prevent us from being able to release smaller patch and feature (backwards compatible) changes. This is mostly a problem in the Optimizely app since other repositories have less incentive to upgrade (especially since the documentation is now versioned).

FWIW, I think it's fine that we release often because our audience (ourselves and third-party Optimizely Apps developers) are either willing to do the upgrade work or are content sticking to the version they are on.

**Proposal to fix this problems:**

We can fix these problems by adopting a new release policy: All developers that want to merge a breaking change must release a version after merging and update the Optimizely app to support it.

If we follow this:

1. Breaking changes should never sit in the "Unreleased" queue for more than a few minutes.
2. OUI should always be ready to release a backwards compatible release.
3. Optimizely should always be on the latest version of OUI to allow backwards compatible changes to be pulled in automatically.

**Potential pain points:** 

1. We currently only care that the Optimizely repo is on the latest version of OUI. This will be more painful if we have to always upgrade multiple repositories.
2. We might begin to second-guess if breaking changes are worth the hassle of upgrading. (I'd also argue that this can be a good thing.)
3. We'll have to communicate to ensure that we're not trying to merge two breaking changes at the same-ish time.

**Longer term solution:**

Tom and I spoke a lot about this, but we may want to investigate splitting the components off into small individual repos. I'm concerned about increased maintenance cost and a (potentially) weird dependency tree, but apparently the [Financial Times has been doing this successfully](http://origami.ft.com/) and it is similar to how [Intuit](https://github.com/inuitcss) is structured. I think this is worth investigating in a few months.

Regardless, the first step towards this would be grouping components within their own directories. I think that is something we should start doing to make our codebase more modular. (I'll create another issue about that later.)

***

@tscanlin, @kwalker3690, @daverau-optimizely – I'd love to hear thoughts and ideas!

**Comment by kwalker3690** [comment]
I love this idea, I think it really encompasses Optimizely's value of #ownership. I also agree that having this kind of friction to making breaking changes is a good thing as well. Ideally we shouldn't be making breaking changes all the time, only when they are absolutely necessary, so this enforces that the developer making the breaking changes feels the burden of those changes. 

I'm glad a longer term solution is being considered however as well, this system of immediately releasing could easily break down as soon as it's not enforced. But maybe that won't be a problem :)

**Comment by tscanlin** [comment]
+1 To this idea as well.

Do any of you have a good idea how painful the v10.0 upgrade will be? Looking at the changelog, I'm guessing pretty painful.

**Comment by danoc** [comment]
@tscanlin – Haha, yes. This one is pretty painful. I'm most of the way there though.

**Comment by tscanlin** [comment]
Oh sweet! I didn't realize you were already doing it.

Let me know if you need any help with this!

**Comment by danoc** [comment]
Closing this because the instructions have been added to `CONTRIBUTING.md`.
