### ISSUE TITLE
Prefix all the classes

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#361]
There are a few benefits towards prefixing/namespacing all classes:
1. When looking at HTML (outside the DevTools) it is easier to find out where a style is defined. For example, an engineer trying to figure out how `.center--child` works might search through the codebase and be confused when the search turns up no SCSS results.
2. Find and replaces become _waaaay_ easier. OUI v10.0.0 has a breaking change that renames `.wrap` to `.wrap` to `.wrap-text`. The find and replace is incredibly hard to do because `wrap` is a very common term in our HTML files. ([This breaking change could have been avoided](https://github.com/optimizely/oui/issues/301) had it already been namespaced.)

The argument for making namespacing optional is that it is not needed if you are starting with a fresh project. I'd say that the two benefits still apply to projects built on top of OUI. This is especially true since we encourage developers to build SCSS partials within their codebase as well.

The downsides of prefixing everything is that it adds a few more characters. This adds a bit of extra weight to the page and clutters the HTML more.

I think the benefits far outweigh the downsides though.

---

@kwalker3690, @daverau-optimizely, @tscanlin – What do y'all think?

**Comment by tscanlin** [comment]
+1 I like this idea!

**Comment by daverau-optimizely** [comment]
Would better naming up front have avoided this breaking change as well? Including more context of what the wrap is doing seems helpful.

I like the idea of better/clear naming of things so if namespacing isn't too heavy of an approach I'm for it.

**Comment by danoc** [comment]
@daverau-optimizely – Yes it would. The breaking change was needed because p13n already has a class called wrap that does something else.

**Comment by danoc** [comment]
So one way to do this would be to modify the SCSS for all classes to temporarily add the prefix along with the current class name.

```css
.wrap,
.oui-wrap {
  foo: bar;
}

.#{$namespace}attention,
.oui-attention {
  bar: foo;
}
```

We can leave it like this for a few months while we tackle renaming the classes in the Optimizely app (maybe even limit this to `v2.css`). Then we'd deploy a custom version, do some testing, and eventually remove the non-prefixed classes.

**Comment by daverau-optimizely** [comment]
This is done, so closing this and will consider a new issue when we get rid of lego and possibly remove the prefix option all together.
