### ISSUE TITLE
Add `pointer-events: none` to classes that disable inputs and buttons

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#365]
We should do some research on the potential side effects and encourage developers to use the `disabled` attribute when possible, but this might be worth doing. cc: @daverau-optimizely

**Comment by daverau-optimizely** [comment]
Good call Dan!

`disabled` only applies to these elements:
```<button>
<input>
<select>
<textarea>
<option>
<optgroup>
<fieldset>```

We'd gain portability by moving to pure CSS and could apply to `<a>` or custom HTML like `<optly-block>` in PreviewUI world.

**Comment by danoc** [comment]
True, but we should also try to ensure that people see this as a last resort for weird scenarios!

@daverau-optimizely – Feel free to make a PR if you'd like.

**Comment by daverau-optimizely** [comment]
Hey @danoc check out my PR and see if this works for ya. Should I have extended/included an existing class vs just writing the property?
