### ISSUE TITLE
Move to a component directory structure

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#368]
Components are often a combination of SCSS, JS, and HTML test files.

**Current file locations:**

Currently, our component SCSS files live in:

```
oui/src/oui/partials/components/_*.scss
```

The JS files live in:

```
oui/src/js/components/*.js
```

And the examples live in:

```
oui/examples/*.html
```

**Proposed file locations:**

All of these component related files would be grouped within a component specific folder. The dialog files, for example, would look like this:

```
src/components/dialog/*.(html|js|scss)
```

This helps us better encapsulate the components and improves code maintainability. Deleting a component and all related files, for example, would be as easy as deleting a directory and removing the references to it.

It also paves the way to adding React (`*.jsx`) files as well as unit and integration tests. Or potentially splitting up OUI into smaller repositories in the future.

(In this world, non-component specific files would either live in `src/common/(js|scss)/*` or `src/base/(js|scss)/*`. I have to think through this part a bit more.)

---

@kwalker3690, @daverau-optimizely, @tscanlin – What do y'all think?

**Comment by daverau-optimizely** [comment]
Sounds like a useful change.

**Comment by tscanlin** [comment]
+1 to collocating components and related files!

Do you think that if we move to react the components should live here or in another repo? Right now I'm thinking maybe both?

Maybe simpler components live here and more specific ones in another repo? Do any of you have thoughts on this?

**Comment by danoc** [comment]
Maybe here initially and then split it out if it becomes a problem? Splitting it out comes at an increased maintenance cost and still has some unknowns as mentioned in the bottom of issue https://github.com/optimizely/oui/issues/360.

@tscanlin – What do you think?

On a sidenote, the [first half of this post](https://medium.com/techspiration-ideas-making-it-happen/future-css-dbc2cb8f1baf#.fgpl3xp6k) explains the benefits of a componentized architecture.

> One of the most relieving developments in modern front-end development has been the move to componentized architecture — that is, thinking about and producing code in which markup, presentation, and business logic are bundled together structurally and/or functionally.

**Comment by tscanlin** [comment]
Yeah, that sounds like a good plan. It will be a while before we get there :)

**Comment by kwalker3690** [comment]
Yes I think the proposed reorg is a great idea!

**Comment by daverau-optimizely** [comment]
Thanks to DanO we're doing this now basically. All new components will be developed this way.
