### ISSUE TITLE
Help icons and tooltip redesign

### ISSUE THREAD

**Issue by silviaamt** [optimizely/oui#375]
All help icons and their tooltips should follow these rules:
- Use the lined, not filled, help icon
- Use the OUI [pop over style](http://design.optimizely.com/docs/oui/11.1.0/#components-popover) for help text 
- Activate the tool tips on click of help icon so that we can embed links

<img width="386" alt="screen shot 2016-04-13 at 11 27 45 am" src="https://cloud.githubusercontent.com/assets/7726331/14509602/f32403a2-0181-11e6-908a-d9e9a57a1c0b.png">

**Comment by tscanlin** [comment]
@danoc right now this icon is just done with css and a pseudo element with a '?' for content. We could stick with that approach or switch to an svg for this. Do you have a preference?

**Comment by danoc** [comment]
Hey @tscanlin – sorry for the delay. Haven't been able to think about this yet. Let's chat when someone is closer to actually implementing it.

**Comment by tscanlin** [comment]
@danoc I actually realized we already have this as an oui icon.

http://design.optimizely.com/docs/oui/11.2.0/#components-icons
#help-16

So I guess its really just a matter of find and replace all over the app. haha ;)

**Comment by tscanlin** [comment]
Also, one other question about this new tooltip behavior @silviaamt 

Click can definitely trigger these tooltips going forward, but what conditions should dismiss the tooltip?

I would imagine clicking outside of it should dismiss it, but how about if users move their mouse outside of it? Should it still dismiss then?

**Comment by daverau-optimizely** [comment]
I like the idea if a click opens a tooltip, a click would be necessary to close it as well. My 2 cents.

**Comment by silviaamt** [comment]
Yep, click to close. The ? icons on Personalization results already work this way, let me know if you need my help to get in and check it out in production.

**Comment by tscanlin** [comment]
Works for me, that behavior makes sense. Should we include a close icon in the top right of the tooltip then, to make sure users can figure it out? Or do you guys think that isn't necessary?

**Comment by silviaamt** [comment]
I don't think it's necessary to modify the pop over style/behavior, it's an
established convention.

Silvia Amtmann
Senior Product Designer  |  Optimizely, Inc.
