### ISSUE TITLE
Research accessibility best practices, share findings, and enforce in pull requests

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#382]
I'll be doing a deep dive into accessibility as we move towards building React components. We can greatly benefit all users if we bake accessibility into these components. A little bit of work will go a long way since we will no longer be duplicating HTML.

### Step 1: Research best practices

This begins with researching best practices. These are a few resources that come to mind, but I'd love pointers towards other places to look.

* Read the [WCAG 2.0](https://www.w3.org/TR/WCAG20/) – These are the latest recommendations from the W3C to make the web more accessible.
* Look at [Salesforce's LDS](https://www.lightningdesignsystem.com/) and 18F's [U.S. Web Design Standards](https://standards.usa.gov/) – These are examples of two design systems that place a huge focus on accessibility.
* [An Alphabet of Accessibility Issues](https://the-pastry-box-project.net/anne-gibson/2014-july-31) – Great list of accessibility issues, some more obvious than others.
* [HTML5 accessibility browser support](https://stevefaulkner.github.io/HTML5accessibility/) – Great checklist of accessible HTML5 features and browser support.

### Step 2: Share findings

There are a few ways to do this, but I'll likely share notes at an upcoming meeting and add an accessibility section to our `CONTRIBUTING.md` file.

### Step 3: Review accessibility in pull requests

I'll start off by creating a checklist of accessibility concerns to review then investigate how we can programmatically enforce some rules. This can likely be done to some extent in automated tests and perhaps there is a accessibility linter I can add to our build system. I'll look into large UI libraries such as Bootstrap and see if they test for accessibility.

**Comment by daverau-optimizely** [comment]
Too broad to do now.
