### ISSUE TITLE
Move helpful Sass code to HTML examples

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#413]
These sections seem like good bits of information to see in code example form or even extended to classes for use as helpers outside the Sass codebase:
1. Brand colors, greys, warning, good news bad news, draft, live
2. Base UI colors for borders, text
3. Font sizes
4. Icon sizes
5. Defaults: spacer unit, dropdown max height, poptip max-width and zindex
6. Shadows, faded as helpers/trumps, flex-center
7. CSS source order as a note or pyramid diagram like Harry Roberts

**Comment by danoc** [comment]
Closing this because it is a bit broad and we'll be tackling most of it in a revamp of the Sass documentation.
