### ISSUE TITLE
Refactor badge color classes

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#423]
These names from v2 should be refactored/renamed to match `.lego-button--highlight` or something similar

```
badge__draft
badge__live
badge__primary
badge__plain
```

![](https://photos-2.dropbox.com/t/2/AACpy3YDY5sl9qoXWA8Yhy6W0Mn9TAI7IBkqI5ilc2S4Rw/12/521178182/png/32x32/3/1466485200/0/2/screenshot_2016-06-20_17.04.39.png/EInDn5YEGLQFIAIoAg/4nGdH9zKXGH9ixt98r5rwQRu3ZaZwoSpPPNP-XBtwl4?size_mode=3&size=1280x960)

**Comment by danoc** [comment]
Going to mark this one as "won't fix" since it's not high priority enough.
