### ISSUE TITLE
Create React Docs v1.0

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#431]
# Version 1 React Docs
- [x] Render react in the docs
- [x] Use react components for the docs
- [x] Get comment doclet meta data working in templates
- [x] Add example code formatted with jsxtostring
- [x] Loop thru external example.js files and render to template `<code><pre>`
- [x] break out example code into external files
- [x] react table component
- [x] props table
- [x] Add loop for table of contents
- [x] required props
- [x] minor style cleanup for example code boxes and borders/soft usage
- [x] start Nav component
- [ ] default prop types (todo: look up defaultVaule before looping over types and check if type is default, then display a label similar to *required)

## Nice to have
- [ ] code component copy/paste (https://clipboardjs.com/)
- [ ] handle component `data={[]}` cleanly — extend/file issue for `reactElementToJSXString`

**Comment by danoc** [comment]
Sweet!!!! 👍  👍  👍  👍  👍  👍

**Comment by danoc** [comment]
Closing this since it's merged. Nice work Dave!!!

**Comment by danoc** [comment]
(Feel free to make individual tasks for the smaller things if you want to track them.)
