### ISSUE TITLE
Why use black for the Dialog close button?

### ISSUE THREAD

**Issue by belohlavek** [optimizely/oui#477]
_See [Dialog](http://design.optimizely.com/docs/oui/12.2.0/?#components-dialog) on the OUI Docs._

Why use a black corner button when you could use something like the [Attention](http://design.optimizely.com/docs/oui/12.2.0/?#components-attention) close button?

**Comment by daverau-optimizely** [comment]
Hi @belohlavek , thanks for pointing this out, very good observation.

We're starting to merge some of the visual styles between our 1.0 and 2.0 products and this will impact OUI. We'll be circling back to update these later and make them more consistent.

**Comment by daverau-optimizely** [comment]
I will check with Designers about this and do it.

**Comment by danoc** [comment]
Going to close this for now. We will be revisiting the component style in a future date once we add a `Dialog` React component.
