### ISSUE TITLE
Update search icon

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#482]
![image](https://cloud.githubusercontent.com/assets/16581943/17348725/21bf98be-58cd-11e6-8ef2-fd1d6f8427f3.png)

**Comment by daverau-optimizely** [comment]
![image](https://cloud.githubusercontent.com/assets/16581943/17348725/21bf98be-58cd-11e6-8ef2-fd1d6f8427f3.png)

**Comment by danoc** [comment]
@daverau-optimizely – This has been done?

**Comment by danoc** [comment]
Oh, issue is still open. Never mind!
