### ISSUE TITLE
Documentation as linked from design.optimizely.com still uses "lego-" prefix in class names

### ISSUE THREAD

**Issue by whatgaul** [optimizely/oui#486]
What is up, gangsters??

I'm using the documentation as linked from http://design.optimizely.com/oui/index.html (links to http://design.optimizely.com/oui/core/api/, which redirect to http://design.optimizely.com/docs/oui/12.2.0/), and the example code still uses the obsolete "lego-" prefix in class names. I've gotten by alright by just inspecting the code of the live examples, but that's suboptimal.

I noticed there are some newer dirs in http://design.optimizely.com/docs/oui/. Maybe this is just a matter of updating links.

~Jon

**Comment by danoc** [comment]
Hi Jon!

Unfortunately we haven't been able to update those docs to serve both internal users (requires the prefix) and third-party developers.

I've made a link that uses P13N to remove the prefix for Apps developers.
http://link.optimizely.com/oui-apps

LMK if that doesn't work!

**Comment by whatgaul** [comment]
Hey Dan! Thanks--that worked after a couple pageloads... this is helpful, but shouldn't Optimizely detect and personalize for external developers automatically? ;)

More broadly though, there's no reason (except of course, time) we couldn't consolidate both the internal and external versions to use a unified "oui-" prefix, right?

**Comment by danoc** [comment]
@whatgaul – Totally! That's the longer term plan:
https://github.com/optimizely/oui/issues/361

**Comment by whatgaul** [comment]
Cool, thanks!
