### ISSUE TITLE
Fix React Icon size prop to output small, medium, large modifiers

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#497]
Was adding React icon examples to the docs and realized that we're using 16/24 for props.size vs `--small`, `--medium`, `--large`.

I'm fine with using all sizes, 16/24/32 or using names, but we should be consistent and correctly apply the OUI helper class for correct sizing.

![screenshot 2016-08-15 14 50 15](https://cloud.githubusercontent.com/assets/16581943/17680937/9ec706d8-62f7-11e6-8043-9cc8e3cb1be4.png)

Would love your thoughts @danoc

**Comment by danoc** [comment]
@daverau-optimizely: Is this still relevant with #549?

**Comment by daverau-optimizely** [comment]
@danoc nope — you've fixed it! Thanks.
