### ISSUE TITLE
Fix activeTab required prop in tabs test

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#522]
Hey @kwalker3690 — heads up there's a missing required prop in your test file:

https://travis-ci.org/optimizely/oui/builds/155491559#L1685

`Running 1 test suite...Warning: Failed prop type: Required prop `activeTab` was not specified in `TabNav.Tab`.`

**Comment by kwalker3690** [comment]
Wat! How did it pass before then?

**Comment by danoc** [comment]
@kwalker3690 – It's a Chrome console error type thing, not a fatal error.
