### ISSUE TITLE
ButtonRow <leftGroup> and <rightGroup> subcomponents

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#537]
Convert this component from data props to subcomponents similar to table, tabnav, blocklist etc.

**Comment by danoc** [comment]
I'd be curious to see what @mjc1283 or @spencerwilson-optimizely think about this. I can't really decide if I like this better or not.

Here's the current component:
https://github.com/optimizely/oui/blob/devel/src/components/ButtonRow/index.js
http://design.optimizely.com/docs/oui/15.1.0/react/#ButtonRow

**Comment by daverau-optimizely** [comment]
Too specific, closing this.
