### ISSUE TITLE
Icon classes don't match to size

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#549]
See `_icons.scss`:
```
  &--small,
  &--12 {
    width: map-fetch($icon, size, small, width);
    height: map-fetch($icon, size, small, height);
  }

  &--medium,
  &--24 {
    width: map-fetch($icon, size, medium, width);
    height: map-fetch($icon, size, medium, height);
  }

  &--large {
    width: map-fetch($icon, size, large, width);
    height: map-fetch($icon, size, large, height);
  }
```

Medium should be `16` and large should be `24`, I think.

**Comment by daverau-optimizely** [comment]
Good catch, I found the names confusing when I was working with the classes so I added the 12 and 24 size options to be more clear what you're getting, but either way I'll fixup the names to better match the sizes.

**Comment by danoc** [comment]
Snagging this one since I'm already doing it to fix another issue.
