### ISSUE TITLE
Select SCSS Component Extends Past 100%

### ISSUE THREAD

**Issue by circAssimilate** [optimizely/oui#570]
The `select` SCSS component extends past 100% width when the length of the text in the `option`‘s is too wide.

**Comment by daverau-optimizely** [comment]
Very tricky issue (http://stackoverflow.com/questions/17408815/fieldset-resizes-wrong-appears-to-have-unremovable-min-width-min-content/17863685#17863685) and setting the `max-width` on the `<fieldset>` element seems to fix this. A quick fix is to use `width--1-1` on the select and it won't break out of the container. We'll fix this in OUI so it's a non-issue going forward.

Here's a codepen of the fix that works in all browsers: http://codepen.io/optidave/full/zoORPW

**Comment by danoc** [comment]
We've fixed this specific example in the app. Will re-visit if needed in the future.
