### ISSUE TITLE
Update vendor prefix rules so older Safari is included in Flexbox output

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#571]
Older Safari (v8) is missing vendor prefixing and Kelly ran into issues when viewing locally. Maybe we should update? Seems like an easy-ish fix.

**Comment by danoc** [comment]
@daverau-optimizely – This is actually in the Optimizely app, not OUI. Check out `postcss.js`and [Autoprefixer](https://github.com/postcss/autoprefixer) if you want to make the change.
