### ISSUE TITLE
_matrix.scss missing variations

### ISSUE THREAD

**Issue by ghost** [optimizely/oui#574]
I believe these are just duplicate declarations:

```
%#{$namespace}matrix,
.#{$namespace}matrix {
  @include matrix(2);
}

%#{$namespace}matrix,
.#{$namespace}matrix {
  @include matrix(3);
}

%#{$namespace}matrix,
.#{$namespace}matrix {
  @include matrix(4);
}
```

and need to be `...matrix--1-2`, etc.

**Comment by daverau-optimizely** [comment]
NEW PHONE — WHO DIS?

**Comment by danoc** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9945144-159451538_2-s1-v1.png?transparent=1&width=246)

**Comment by kwalker3690** [comment]
Isn't this a violation of the restraining order?

**Comment by tomtick** [comment]
Oh, great. Kelly is still around.

**Comment by tomtick** [comment]
@danoc found with http://stylelint.io/user-guide/rules/no-duplicate-selectors/

**Comment by danoc** [comment]
Ohhh, awesome. +1 for stylelint.

**Comment by danoc** [comment]
Closing this because it's not high priority right now.
