### ISSUE TITLE
OUI docs get really slow to navigate after a few seconds

### ISSUE THREAD

**Issue by asaschachar** [optimizely/oui#592]
Trying to scroll around the OUI docs and the page gets really slow and unresponsive:

http://design.optimizely.com/docs/oui/17.3.2/sass/

**Comment by daverau-optimizely** [comment]
Did some quick investigating into this and JavaScript is interacting with computed style calculations triggering the `recalculate style` and `layout` performance issues seen here:

<img width="1199" alt="docs-perf" src="https://cloud.githubusercontent.com/assets/16581943/18924813/6ada98bc-8566-11e6-8aa3-5ebbedf0b9a9.png">

Last week I traced this back to a single release where we introduced a JS refactor for dropdowns, etc and you can see a difference between the the last version [9](http://design.optimizely.com/docs/oui/9.0.8/#objects-dropdown) docs vs [10](http://design.optimizely.com/docs/oui/10.0.0/#components-dropdown). Click the dropdown and notice the lag time in v10 that is nearly instant in 9.

Going forward the new CSS docs would only ship with React component JS and nothing more, but performance-wise this still might be an issue at the render/paint level.

**Comment by danoc** [comment]
This will be fixed in https://github.com/optimizely/oui/issues/686.
