### ISSUE TITLE
Button: need full-width option to be separate from full

### ISSUE THREAD

**Issue by mjc1283** [optimizely/oui#615]
Talked to @danoc about this - I need to create a Button that has full width with respect to its container, but is still 'small'-sized.

**Comment by daverau-optimizely** [comment]
@danoc is this just changing the size prop `<Button size="full">` to something like `<Button size="small" width="full">`?

**Comment by danoc** [comment]
@daverau-optimizely – Yeah, essentially just moving `width` outside of `size` with a `default` and `full` option.

It'd be a breaking change, but not too painful of an upgrade.
