### ISSUE TITLE
Allow table elements to be passed className

### ISSUE THREAD

**Issue by jordangarcia** [optimizely/oui#642]
Table is so generic that a lot of times we need to use our own classNames in specific cases

Example: on the results page

``` js
<Table.TR className={ classNames({
        'epsilon': true,
        'weight--normal': true,
        'color--good-news': !data.isBaseline && data.lift.isSignificant && data.lift.value >= 0,
        'color--bad-news': !data.isBaseline && data.lift.isSignificant && data.lift.value < 0,
      })}>
```

**Comment by raykhenberg** [comment]
I approve this message, would like to see this, right now I'm wrapping all the content in each TD with a span that contains all of these classes.

**Comment by daverau-optimizely** [comment]
@inakiaranzadi-optimizely what are your thoughts on this for React going forward? Open up some stuff to using arbitrary classes, or something else to handle text perhaps?

**Comment by daverau-optimizely** [comment]
Closing this, seems like using classNames works okay for now.
