### ISSUE TITLE
OverlayWrapper should have a prop `hideOnClick={ false }`

### ISSUE THREAD

**Issue by jordangarcia** [optimizely/oui#654]
This will allow a non-hacky way to do https://github.com/optimizely/optimizely/blob/devel/src/www/frontend/src/js/bundles/p13n/sections/results/components/results_header/index.js#L90-L96

In addition OverlayWrapper should expose some `context.hideOverlayWrapper()` to allow components to manually control this, similar to dropdown

**Comment by danoc** [comment]
Just put out a PR for the first part of this and created a separate issue (#657) for exposing the hide function.
