### ISSUE TITLE
Add ability to highlight text from a disabled input

### ISSUE THREAD

**Issue by kwalker3690** [optimizely/oui#655]
Somehow I ran into this twice today, it is not possible to select the text from a disabled input, and we often use disabled inputs in places where someone might just want to copy the value of the input to use somewhere else

**Comment by danoc** [comment]
@kwalker3690 – You might want to use the `isReadOnly` prop instead. Not allowing text selection is the default browser behavior.

https://stackoverflow.com/questions/4726715/disabled-input-that-allows-text-selection
