### ISSUE TITLE
Unstyled button should have more sensible styles

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#674]
The current implementation doesn't work as expected because it doesn't behave like normal text. This might be better:

```css
margin: 0;
padding: 0;
border: 0;

background: transparent;
font-size: inherit;
text-align: inherit;
line-height: inherit;
```

**Comment by danoc** [comment]
This may be helpful:
https://github.com/optimizely/oui/pull/675/commits/4f3bf19dd6a4c87f18bfe238765112089ceb0661

**Comment by daverau-optimizely** [comment]
Good enough fix for now.
