### ISSUE TITLE
Allow users to opt-into LEGO namespacing for all classes

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#68]
Existing projects that use LEGO would benefit from this, but make it opt-in since it isn't important for projects that are created on top of LEGO.

The one downside I can think of (which @tscanlin mentioned) is that it becomes harder to search for the class in the codebase. However, the `.lego-` prefix will at least indicate that the code lives in Core.

**Comment by tscanlin** [comment]
+1. Should make the switch to 'oui-' later on a bit easier.

**Comment by danoc** [comment]
@tomgenoni – Could you take this on before the large breaking release? Seems like you already know how to do it.

**Comment by tomgenoni** [comment]
yup

**Comment by danoc** [comment]
PR is here: https://github.com/optimizely/lego/pull/93

**Comment by danoc** [comment]
@tomgenoni – I noticed that the PR only addressed the classes that already had the `lego` prefix. Personally, I think it should be applied to all selectors (like [`.link`](https://github.com/optimizely/lego/blob/master/src/core/partials/base/_links.scss)) so that we can:

1) **Prevent naming collisions** – We don't currently have any collisions between Core and the Optimizely app, but adopting the convention of namespacing all selectors can prevent future collisions. Adding a new class `.form--wide` to Core, for example, could break existing forms in the Optimizely app. We should be able to add new features to Core without worrying about the downstream effects. Namespacing all selectors is one way to do that.
2) **Make it easier to see what classes are coming from Core**.

**Comment by tomgenoni** [comment]
I'm not opposed to adding it to `.link` but should it apply to all classes including trumps?

**Comment by tomgenoni** [comment]
The default should be prefix-less classes when starting a new project. There's no point, as far as I can tell, of switching to `oui-` unless there are exiting collisions.

**Comment by danoc** [comment]
I think it should definitely be applied all classes within partials. It's not _as important_ for trumps because applications have to opt-in to specific trumps whereas the partials loaded are determined by `_core-partials.scss`.

Let's discuss in person if I'm making no sense.

**Comment by danoc** [comment]
Closing this. I don't think it's worth the hassle.
