### ISSUE TITLE
Migrate icons

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#732]
Rework React icons to avoid the loader webpack issues; include SVG in the component.

**Comment by daverau-optimizely** [comment]
Consider babel-plugin-inline-react-svg

**Comment by inakiaranzadi-optimizely** [comment]
I am working in a React SVG version of the OUI icons. 
Features: 
- [x] inline svgs
- [x] dynamic created based on json object
- [x] props to control different attributes of the svg
- [ ] fix alignment
- [ ] register as npm package
- [ ] write tests
- [ ] writer readme (how to, description, etc)

**Comment by inakiaranzadi-optimizely** [comment]
done and working
