### ISSUE TITLE
Input oui react component should accept numbers as a value type

### ISSUE THREAD

**Issue by amy-chiu** [optimizely/oui#736]
Currently I'm getting the following in my browser console for the Input oui react component:

`Warning: Failed propType: Invalid prop `value` of type `number` supplied to `Input`, expected `string`.`

Can we change our Input oui react component to accept numbers as well for a value type?

**Comment by daverau-optimizely** [comment]
@inakiaranzadi-optimizely this might be a good issue for you to tackle as a starter project. Also #737

**Comment by inakiaranzadi-optimizely** [comment]
Sure thing, I'll look this up. @amy-chiu @daverau-optimizely

**Comment by daverau-optimizely** [comment]
Fixed
