### ISSUE TITLE
Allow Attention React Oui Component To Accept Other React Oui Components As Children

### ISSUE THREAD

**Issue by amy-chiu** [optimizely/oui#737]
Getting the following warning in my browser console:

Warning: Failed propType: Invalid prop `children` of type `array` supplied to `Attention`, expected `string`. 

Currently I have the following code:
`<Attention alignment="left" type="warning" testSection="key-change-warning">
              Changing the snippet key will break your existing snippet implementation.
              If you choose to save this change, please remember to update the snippet
              code in the <Code isHighlighted={ true } type="inline" language="html">{ '<head>' }</Code> tag of your site.
            </Attention>`

We should be able to provide the react oui component <Code> within the react oui component <Attention>

**Comment by raykhenberg** [comment]
+1 on this, I'm seeing it on the results page because I'm adding an anchor tag in there.

**Comment by daverau-optimizely** [comment]
Fixed via #861
