### ISSUE TITLE
Replace SCSS-lint (Ruby) with sass-lint (JS)

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#762]
- [ ] Remove all references to code/tools that depend on Ruby, like SCSS-lint. JavaScript or 💀

**Comment by angushtlam** [comment]
Is `scss-lint` the only Ruby dependency on the repo? I don't see the build process using any Ruby (in `.travis.yml`), so removing Ruby should be as simple as replacing the linter

This one looks pretty promising https://github.com/sasstools/sass-lint, are there any other Ruby dependencies other than `scss-lint`?

**Comment by daverau-optimizely** [comment]
Via @jamesopti: Our grunt package for css building (grunt-sass) doesnt support yet
TODO: OUI team confirm how we build CSS in optimizely.git and see if grunt-sass is still the right lib
