### ISSUE TITLE
Create UI component checklist

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#806]
Work with @jackschlotthauer-optimizely to create a UI checklist we can go thru and test components before releasing and have more confidence we're solving the right problems upfront.

# Work-in-progress...
1. Include `data-oui-component={ true }` on the highest parent HTML element being rendered by your component

**Comment by jackschlotthauer-optimizely** [comment]
This is the way we do it as front-end engineers here @ Optimizely.

https://optimizely.atlassian.net/wiki/spaces/ENG/pages/168646438/Frontend+Checklist+Definition+of+Done
