### ISSUE TITLE
Freeze OUI to React version 15.1.0 

### ISSUE THREAD

**Issue by inakiaranzadi-optimizely** [optimizely/oui#819]
Review process: 
- [x] Freeze OUI to React version 15.1.0
- [x] Update react-oui-icons to 0.8.0
- [x] Review and update to `prop-types` standalone pkg
- [x] Update dependencies that doesn't break current version
- [x] Fix any warning or errors

**Comment by daverau-optimizely** [comment]
Included in the latest release:
1) Updating `react-oui-icons` to 0.8.0
2) Update docs to use `prop-types` standalone
3) Update <Icon/> component to use `prop-types` standalone package
