### ISSUE TITLE
isReadOnly Input component is confusing because the blue outline makes it look editable

### ISSUE THREAD

**Issue by jessicalc** [optimizely/oui#883]
This came up in the FullStack MVT Bug Bash: 
https://docs.google.com/document/d/1wbRfpvxaxBUs4SsZNpd9Bk8GiEsSKP8dIrCDGvTA-NE/edit?ts=5a3afade#bookmark=id.x1s4yxy0oh7n 

> Very small nit: On the ‘Combinations’ tab, you can sort of select all of the text fields (and highlight all the text in a text field), making them feel like they should be editable. But then they aren’t. (‘price, ascending’ is somewhat selected here) [[APP-1734](https://optimizely.atlassian.net/browse/APP-1734)]

![confusing-fields](https://user-images.githubusercontent.com/729524/34745382-2a0104ac-f545-11e7-801c-707345ecb6f0.gif)

**Comment by daverau-optimizely** [comment]
Fixed in latest release, thanks to keen eyes from @jessicalc
