### ISSUE TITLE
Overhaul docs deploy process

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#889]
This is the list of tasks so far. Please add anything you can think of that I haven't covered! @patrickgilbert-optimizely @inakiaranzadi-optimizely 

## DevOps
- [ ] Combine design-dot and OUI docs into one repo
- [ ] Move from EC2/Ubuntu to S3
- [ ] Update Travis CI job so it deploys to S3
- [ ] Update `.npmignore` file to include docs dist
- [ ] Include/remove from `.gitignore` docs/dist in GitHub repo

## Redirect
- [ ] Update Travis CI job to update S3 redirect to /latest on deploy
- [ ] Update oui-icons go links to react icons storybook

## Clean up
- [ ] Deprecate/remove personas with password protection
- [ ] Remove encrypted cred file

## Archive
- [ ] Upload previous versions of oui docs to S3 (archive)
- [ ] Create branded index for previous versions? Dropdown picker?

## Done
- [ ] Test everything works! Redirects, images/files, archive
- [ ] DNS update from ec2 to s3

**Comment by patrickgilbert-optimizely** [comment]
This is great from a deployment perspective.

From a migration (ubuntu -> s3), you'll need to get a DNS update in there somewhere, once you're ready to switch the live site.

**Comment by daverau-optimizely** [comment]
Done since we've moved to Heroku. Will get with Patrick to update DNS when we're ready to go live in Feb.
